### ISSUE TITLE
Facebook and Google + 

### ISSUE THREAD

**Issue by garciaae** [wuman/android-oauth-client#11]
Is there an easy way to manage both connections? Does anybody knows which ones are the right parameters to set for doing a proper connection?

**Comment by axd1967** [comment]
then this library should say

*"Android OAuth Client (android-oauth-client) is a library that helps to easily add an OAuth flow* **except Google or FB** *to an existing Android application."*

rather than 

*"Android OAuth Client (android-oauth-client) is a library that helps to easily add an OAuth flow to an existing Android application."*

no?

**Comment by garciaae** [comment]
It makes sense to change it.
